#!/bin/bash
# Convert code to formatted PDF and print it
FILEPATH="$2"
FILENAME="$(basename $FILEPATH)"
OUTNAME="/tmp/$FILENAME.md"
PDFNAME="/tmp/$FILENAME.pdf"
echo "% $FILENAME" > $OUTNAME
echo "\`\`\`$1" >> $OUTNAME
cat $FILEPATH >> $OUTNAME
echo "\`\`\`" >> $OUTNAME
pandoc $OUTNAME \
    -V geometry:margin=2cm \
    -o $PDFNAME
lpr $PDFNAME
rm $OUTNAME
rm $PDFNAME

